apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zvh405lic-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zvh405lic-go 
  name: zvh405lic-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zvh405lic-go 
