apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zvh405lic-go 
  janus-idp.io/tekton: zvh405lic-go
  backstage.io/kubernetes-id: zvh405lic-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zvh405lic-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml